<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Balu" ignored="0" name="Validation Title" tests="2" failures="2" timestamp="28 Dec 2019 13:27:49 GMT" time="193.625" errors="0">
  <testcase name="navigationHomepage" time="2.132" classname="Academy.ValidateTitle">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Academy.ValidateTitle.navigationHomepage(ValidateTitle.java:50)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- navigationHomepage -->
  <testcase name="navigationHomepage" time="2.137" classname="Academy.ValidateTitle">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at resources.base.getScreenShot(base.java:67)
at Academy.Listeners.onTestFailure(Listeners.java:30)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- navigationHomepage -->
</testsuite> <!-- Validation Title -->
